### ISSUE TITLE
RHEL exercise 1.3 not shown in Github pages

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#772]
##### SUMMARY

Github pages don't show RHEL exercise 1.3 currently:
https://ansible.github.io/workshops/exercises/ansible_rhel/1.3-playbook/
![Screenshot from 2020-04-08 14-26-42](https://user-images.githubusercontent.com/1998084/78784083-fd549e00-79a4-11ea-9607-e18f22abc632.png)

##### ISSUE TYPE

 - Bug Report

##### FURTHER DETAILS

In PR #760 the file "[index.html](https://github.com/ansible/workshops/blob/devel/exercises/ansible_rhel/1.3-playbook/index.html)" was introduced to the directory of the the RHEL exercise. This leads github pages to just render the index.html file instead of the README, effectively making the exercise unreadable.

##### SUGGESTED FIXES

It looks like the index.html file is there to provide students a solution file. This should be copied to a subdirectory though to avoid rendering problems.

**Comment by IPvSean** [comment]
@liquidat that seems to fix it, thanks for finding this!

sorry @goetzrieger if you hit any problems here

**Comment by liquidat** [comment]
Fixed by PR #777

**Comment by DarrickLeong** [comment]
Hi is this issue fixed? when I accessed the general workshop link https://ansible.github.io/workshops/exercises/ansible_rhel/1.3-playbook/ 
I am still seeing the "Apache is running fine" instead of the workshop steps.

**Comment by IPvSean** [comment]
its in devel branch, it will go live in the next release
